steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs8
      - --trigger-http
      - --source=./more/extra/method1/  # Function source files
      - --entry-point=small  # Function entry point
      - hello-gcf-1 # Function name

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'hello-gcf-2', '--trigger-http', '--runtime', 'nodejs8', '--entry-point', 'f']
    dir: ''