steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - beta
      - deploy
      - --trigger-http
      - --source=.
      - --entry-point=f
      - hello-gcf # Function name