steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './adapter.js', './more/extra/method1/adapter.js']
    waitFor: ['-']  # The '-' indicates that this step begins immediately.
    id: 'copy-adapter-for-method1'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://play_with_data/vars.yaml', './more/extra/method1/vars.yaml']
    waitFor: ['-']  # The '-' indicates that this step begins immediately.
    id: 'getting-vars-for-method1'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs8
      - --trigger-http
      - --source=./more/extra/method1/  # Function source files
      - --entry-point=small  # Function entry point
      - hello-gcf-1 # Function name
      - --env-vars-file=./more/extra/method1/vars.yaml

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './adapter.js', './more/extra/method2/adapter.js']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://play_with_data/vars.yaml', './more/extra/method2/vars.yaml']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs8
      - --trigger-http
      - --source=./more/extra/method2/  # Function source files
      - --entry-point=small  # Function entry point
      - hello-gcf-2 # Function name
      - --env-vars-file=./more/extra/method2/vars.yaml

#
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['functions', 'deploy', 'hello-gcf-2', '--trigger-http', '--runtime', 'nodejs8', '--entry-point', 'f']
#    dir: './'