steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs8
      - --trigger-http
      - --source=.
      - --entry-point=f
      - hello-gcf # Function name

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'hello-gcf', '--trigger-http', '--runtime', 'nodejs8', '--entry-point', 'f']
    dir: './'